Add buildargs
codecentric/springboot-maven3-centos pull request #7
Opened 2016-09-16 00:08 UTC by luiscoms

* Add `$APP_TARGET` and `$MVN_ARGS` env var
* Fix tests for Mac when running `make test`

Thanks for @miklosbarabas for changes

2016-09-16 07:06 UTC, britter commented
Wow, very nice! I'll need some time to test this change with my demo app. Thank you!

2016-09-18 17:11 UTC, britter commented on s2i/bin/run
> +java $JAVA_OPTS -jar `find $APP_TARGET -name *.jar`
$APP_TARGET should be set to target by default if it is not set.

2016-09-18 17:12 UTC, britter requested changes

2016-09-19 14:39 UTC, luiscoms commented
I just added target dir to default value

2016-09-20 07:04 UTC, britter commented
@luiscoms when I run:

```
docker build -t codecentric/springboot-maven3-centos .
s2i build https://github.com/codecentric/springboot-sample-app codecentric/springboot-maven3-centos springboot-sample-app
```

I get:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:46 min
[INFO] Finished at: 2016-09-20T06:58:00+00:00
[INFO] Final Memory: 31M/75M
[INFO] ------------------------------------------------------------------------
ERROR: chgrp: cannot access './.pki/nssdb': Permission denied
ERROR: chmod: cannot access './.pki/nssdb': Permission denied
ERROR: find: './.pki/nssdb': Permission denied

ERROR: An error occurred: non-zero (13) exit code from codecentric/springboot-maven3-centos
```

Does this work for you?

2016-09-21 12:42 UTC, luiscoms commented
I Just run `make test`, that command build the image and run test-app

2016-09-21 23:35 UTC, luiscoms commented
I Just run `make test`, and the tests are passing.
I ran your command and image built successfully

2016-09-22 06:02 UTC, britter approved these changes

2016-09-22 06:04 UTC, merged

2016-09-22 06:04 UTC, britter commented
Thank you!